import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mutou",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        rel: "icon",
        media: "(prefers-color-scheme: light)",
        type: "image/x-icon",
        url: "/images/favicon.ico",
        href: "/images/icon.svg",
      },
      {
        rel: "icon",
        media: "(prefers-color-scheme: dark)",
        type: "image/svg+xml",
        url: "/images/icon.svg",
        href: "/images/icon.svg",
      },
    ],
  },
};

const navItems = [
  { label: "Home", href: "/" },
  { label: "About", href: "/about" },
  { label: "Contact", href: "/contact" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "min-h-dvh ")}>
        <header className="container h-16 flex items-center border-b justify-between">
          <h1 className="font-bold">LOGO</h1>
          <ul className="flex gap-4">
            {navItems.map((item) => (
              <li key={item.label}>
                <Button variant="ghost" asChild>
                  <Link href={item.href}>{item.label}</Link>
                </Button>
              </li>
            ))}
          </ul>
        </header>

        {/* <main className="flex-1 relative">{children}</main> */}
        <main>{children}</main>

        <footer className="container sticky top-full h-16 flex items-center border-t">
          <p>&copy;ainosh</p>
        </footer>
      </body>
    </html>
  );
}
